import user from "./state";
import { computed } from "Vue";
import role from "@/hooks/roles";

type Actions =
  | "CreateUser"
  | "ReadUser"
  | "UpdateUser"
  | "DeleteUser"
  | "CreatePkg"
  | "ReadPkg"
  | "UpdatePkg"
  | "DeletePkg"
  | "CreateLabel"
  | "ReadLabel"
  | "UpdateLabel"
  | "DeleteLabel"
  | "CreateTrack"
  | "ReadTrack"
  | "UpdateTrack"
  | "DeleteTrack"
  | "CreateRoute"
  | "ReadRoute"
  | "UpdateRoute"
  | "DeleteRoute"
  | "CreateShipment"
  | "ReadShipment"
  | "UpdateShipment"
  | "DeleteShipment"
  | "CreateAgent"
  | "ReadAgent"
  | "UpdateAgent"
  | "DeleteAgent"
  | "CreateRole"
  | "ReadRole"
  | "UpdateRole"
  | "DeleteRole"
  | "CreateAlert"
  | "ReadAlert"
  | "UpdateAlert"
  | "DeleteAlert"
  | "CreateGeneral"
  | "ReadGeneral"
  | "UpdateGeneral"
  | "DeleteGeneral"
  | "CreateAdmin"
  | "ReadAdmin"
  | "UpdateAdmin"
  | "DeleteAdmin"
  | "CreateDb"
  | "ReadDb"
  | "UpdateDb"
  | "DeleteDb"
  | "CreateDept"
  | "ReadDept"
  | "UpdateDept"
  | "DeleteDept"
  | "CreatePercelConfig"
  | "ReadPercelConfig"
  | "UpdatePercelConfig"
  | "DeletePercelConfig"
  | "CreateLabelConfig"
  | "ReadLabelConfig"
  | "UpdateLabelConfig"
  | "DeleteLabelConfig"
  | "CreateInvoiceConfig"
  | "ReadInvoiceConfig"
  | "UpdateInvoiceConfig"
  | "DeleteInvoiceConfig";
export default {
  can: (action: Actions) => user.permission[action],
};
