export default {
  roles: [
    [1, "Parcel Manager", "Pkg"],
    [11, "Parcel Label", "Label"],
    [15, "Tracking Manager", "Track"],
    [2, "Customer Manager", "User"],
    [3, "Shipment Route Manager", "Route"],
    [4, "Shipment Process Manager", "Shipment"],
    [5, "Employees Manager", "Agent"],
    [6, "Roles Manager", "Role"],
    [7, "Notification Manager", "Alert"],
    [9, "General Settings", "General"],
    [8, "Admin Settings Manager", "Admin"],
    [12, "Dashboard", "Db"],
    [10, "Department Manager", "Dept"],
    [13, "Parcel Configuration", "ParcelConfig"],
    [16, "Label Configuration", "LabelConfig"],
    [14, "Invoice Configuration", "InvoiceConfig"],
    [17, "Accounting & Invoice", "Invoice"],
    // [16, "Department Manager", "Dept"],
    // [17, "Department Manager", "Dept"],
  ],
  companyRoles: [
    [13, "Dashboard", "CompanyDb"],
    [10, "Department Manager", "Dept"],
    [14, "Company Configuration", "CompanySetting"],
  ],
};
