export const btnMixins = {
  props: {
    tile: Boolean,
    fab: Boolean,
    icon: { type: [Boolean] },
    dense: Boolean,
    secondary: Boolean,
    tertiary: Boolean,
    xLarge: Boolean,
    large: Boolean,
    small: Boolean,
    xSmall: [Boolean, Object],
    disabled: {},
    to: {},
    loading: [Boolean, Object],
    prependIcon: {},
    appendIcon: {},
    color: { default: "blue" },
    textColor: { default: "gray" },
    type: { default: "button" },
    dark: Boolean,
    text: Boolean,
  },
};
