export const inputMixins = {
  props: {
    dark: Boolean,
    password: Boolean,
    value: {
      type: [String, Object, Number],
    },
    items: {},
    name: String,
    id: String,
    itemText: String,
    itemValue: String,
    type: { default: "text" },
    valueFormat: Function,
    combobox: Boolean,
    select: Boolean,
    autoComplete: Boolean,
    rounded: Boolean,
    menu: Boolean,
    textarea: Boolean,
    inputClass: [String, Object],
    loading: [Boolean, Object],
    tile: Boolean,
    readonly: Boolean,
    disabled: Boolean,
    dense: Boolean,
    clearable: Boolean,
    prependIcon: String,
    placeholder: String,
    maxlength: Number,
    prependInnerIcon: String,
    prefix: String,
    suffix: String,
    appendIcon: String,
    appendInnerIcon: String,
    label: String,
  },
};
